# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  workflow_dispatch: # allows manual trigger
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "simple"
  simple:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      pw: ${{ steps.step1.outputs.pw }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        id: step1
        run: echo ${{ secrets.SUPER_SECRET_PASSWORD }} >> "$GITHUB_OUTPUT"

  matrix:
    runs-on: ubuntu-latest
    needs: simple
    steps:
      - env:
          pw: ${{ needs.simple.outputs.pw }}
        run: echo $pw >> "$GITHUB_OUTPUT"